In [2]:
# question 1 (array)

import numpy
def arrays(arr):
    return numpy.array(arr,float)[::-1]
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [3]:
# question 2 ( shape and reshape)

import numpy
l=input().split()
a=numpy.array(l,dtype=int).reshape(3,3)
print(a)



1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# question 3 (transpose and flatten)

import numpy
our_array = numpy.array([input().split() for y in range(int(input().split()[0]))], int)
print(numpy.transpose(our_array), our_array.flatten(), sep="\n")


2 2 
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
# question 4 (concatenate)

import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [6]:
 # question 5 (zeroes and one)
 
 import numpy
a=list(map(int,input().split()))
z=numpy.zeros(a,dtype=numpy.int)
o=numpy.ones(a,dtype=numpy.int)
print(z)
print(o)


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
# question 6 (eye and identity)

import numpy
m,n=map(int,input().split())
numpy.set_printoptions(sign=" ")
print(numpy.eye(m,n))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
# question 7 (array mathematics)

import numpy
n,m=list(map(int,input().split()))
mat1=numpy.array([input().split() for i in range(n)],int)
mat2=numpy.array([input().split() for i in range(n)],int)
print(mat1+mat2)
print(mat1-mat2)
print(mat1*mat2)
print(mat1//mat2)
print(mat1%mat2)
print(mat1**mat2)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [9]:
# question 8 (floor, ceil and rint)

import numpy
numpy.set_printoptions(legacy="1.13")
a=list(map(float,input().split()))
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))





1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [10]:
# question 9 (sum and prod)

import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
S=numpy.sum(A,axis=0)
print(numpy.product(S,axis=0))



2 2
 1 2
3 4
24


In [11]:
# question 10 (min and max)

import numpy
m,n=list(map(int,input().split()))
a=numpy.array([input().split() for i in range(m)],int)
M=numpy.min(a,axis=1)
print(numpy.max(M))


4 2
2 5
3 7
1 3
4 0
3


In [12]:
# question 11 (mean , var and std)

import numpy
m,n=list(map(int,input().split()))
a=numpy.array([input().split() for i in range(m)],int)
print(numpy.mean(a,axis=1))
print(numpy.var(a,axis=0))
print(numpy.around(numpy.std(a),decimals=11))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [13]:
# question 12 (dot and cross)

import numpy
n=int(input())
a=numpy.array([input().split() for i in range(n)],int)
b=numpy.array([input().split() for i in range(n)],int)
print(numpy.dot(a,b))



2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [14]:
# question 13 (inner and outer)

import numpy
a=list(map(int,input().split()))
b=list(map(int,input().split()))
print(numpy.inner(a,b))
print(numpy.outer(a,b))



0 1
2 3
3
[[0 0]
 [2 3]]


In [15]:
# question 14 (polynomials)

import numpy
a = list(map(float, input().split()))
#m = input()
print(numpy.polyval(a,float(input())))


1.1 2 3
0
3.0


In [16]:
# question 15 (linear algebra)

import numpy
print(round(numpy.linalg.det(numpy.array([input().split() for _ in range(int(input()))],float)),2))


2
1.1 1.1
1.1 1.1
0.0
